export const restaurants = [
  {
    id: 1,
    name: "Soy Restaurant",
    location: "Kiyovu, Kigali",
    cuisine: "African · Fusion · International",
    rating: 4.2,
    reviews: 124,
    status: "OPEN",
    type: "RESTAURANT",
    image: "/soy.jpg",
  },
  {
    id: 2,
    name: "M Hotel & Spa",
    location: "Nyarutarama, Kigali",
    cuisine: "Fine Dining · Continental",
    rating: 4.8,
    reviews: 302,
    status: "OPEN",
    type: "HOTEL",
    image: "/hotel.jpg",
  },
  {
    id: 3,
    name: "Sundowner",
    location: "Kacyiru, Kigali",
    cuisine: "Craft Beers · Pub Food",
    rating: 4.0,
    reviews: 88,
    status: "CLOSES 02:00",
    type: "PUB",
    image: "/sundowner.jpg",
  },
  {
    id: 4,
    name: "Aroma Cafe",
    location: "Remera, Kigali",
    cuisine: "Coffee · Pastries · Light Bites",
    rating: 4.5,
    reviews: 210,
    status: "OPEN",
    type: "CAFE",
    image: "/aroma.jpg",
  },
  {
    id: 5,
    name: "Planet Burger",
    location: "Gasabo, Kigali",
    cuisine: "American · Fast Food",
    rating: 3.8,
    reviews: 56,
    status: "CLOSED",
    type: "RESTAURANT",
    image: "/planet.jpg",
  },
  {
    id: 6,
    name: "Choose Kigali",
    location: "Nyarugenge, Kigali",
    cuisine: "Local · Pan-African",
    rating: 4.3,
    reviews: 178,
    status: "OPEN",
    type: "RESTAURANT",
    image: "/choose.jpg",
  },
];
