export { authAPI }          from "./auth";
export type { AuthUser }    from "./auth";
export { restaurantsAPI }   from "./restaurants";
export { ordersAPI }        from "./orders";
export { menusAPI }         from "./menus";
export { tablesAPI }        from "./tables";
export { staffAPI }         from "./staff";
export { paymentsAPI }      from "./payments";
export { reviewsAPI }       from "./reviews";
export { notificationsAPI } from "./notifications";
export { analyticsAPI }     from "./analytics";
export { customersAPI }     from "./customers";
export { settingsAPI }      from "./settings";
export { auditLogsAPI }     from "./auditLogs";
export { getErrorMessage, normalizeDoc, normalizeList } from "./utils";
export { default as api }   from "./axios";
